CREATE TYPE "EstadoIncidencia" AS ENUM ('PENDIENTE', 'DERIVADA_A_SIGOM', 'RESUELTA');

ALTER TABLE "Incidencia" ALTER COLUMN "estado" DROP DEFAULT;
ALTER TABLE "Incidencia"
  ALTER COLUMN "estado" TYPE "EstadoIncidencia"
  USING (
    CASE "estado"
      WHEN 'PENDIENTE' THEN 'PENDIENTE'
      WHEN 'EN_REVISION' THEN 'PENDIENTE'
      WHEN 'DERIVADA_A_SIGOM' THEN 'DERIVADA_A_SIGOM'
      WHEN 'RESUELTA' THEN 'RESUELTA'
      WHEN 'CERRADA' THEN 'RESUELTA'
      ELSE 'PENDIENTE'
    END
  )::"EstadoIncidencia";
ALTER TABLE "Incidencia" ALTER COLUMN "estado" SET DEFAULT 'PENDIENTE';
